--- #YAML:1.0
name: CGI-Session-PureSQL
version: 0.54
author:
  - Mark Stosberg <mark@summersault.com>
abstract: |-
  Pure SQL driver with no embedded Perl stored in the database
license: perl
requires:
  CGI::Session: 3.95
  Date::Calc: 0
  SQL::Abstract: 0
provides:
  CGI::Session::PureSQL:
    file: lib/CGI/Session/PureSQL.pm
    version: 0.54
  CGI::Session::Serialize::SQLAbstract:
    file: lib/CGI/Session/Serialize/SQLAbstract.pm
    version: 0.54
generated_by: Module::Build version 0.2606
